WARNING 2025-05-29 08:22:38 log 92985 6205878272 Not Found: /categories/
WARNING 2025-05-29 08:23:01 log 92985 6205878272 Not Found: /category
WARNING 2025-05-29 08:23:35 log 92985 6205878272 Not Found: /seller/category
ERROR 2025-05-29 08:24:15 log 93581 6193852416 Internal Server Error: /seller/categories/
Traceback (most recent call last):
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/Desktop/work-history/lotipoti-shop/markcc-seller/markcc_with_seller/sellers/decorators.py", line 14, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/Desktop/work-history/lotipoti-shop/markcc-seller/markcc_with_seller/category/views.py", line 24, in category
    seller = request.seller  # Set in the seller_required decorator
             ^^^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'seller'
ERROR 2025-05-29 08:24:16 log 93581 6193852416 Internal Server Error: /seller/categories/
Traceback (most recent call last):
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/Desktop/work-history/lotipoti-shop/markcc-seller/markcc_with_seller/sellers/decorators.py", line 14, in _wrapped_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/Desktop/work-history/lotipoti-shop/markcc-seller/markcc_with_seller/category/views.py", line 24, in category
    seller = request.seller  # Set in the seller_required decorator
             ^^^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'seller'
WARNING 2025-05-29 12:26:53 log 3894 6301577216 Not Found: /favicon.ico
WARNING 2025-06-13 06:36:34 log 32235 6131724288 Not Found: /favicon.ico
WARNING 2025-06-13 06:44:36 log 37694 6163771392 Not Found: /favicon.ico
WARNING 2025-06-13 06:49:22 log 39411 6145748992 Not Found: /favicon.ico
WARNING 2025-06-13 06:51:07 log 40269 6180859904 Not Found: /favicon.ico
WARNING 2025-06-13 07:05:12 log 41553 6225817600 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 07:05:13 log 41553 6225817600 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 07:05:13 log 41553 6225817600 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 08:06:05 log 41553 6276296704 Bad Request: /auth/login/
WARNING 2025-06-13 08:11:49 log 41553 6225817600 Not Found: /favicon.ico
ERROR 2025-06-13 08:26:09 log 42175 6191951872 Service Unavailable: /
WARNING 2025-06-13 08:33:52 log 42175 6326562816 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 08:33:59 log 42175 6326562816 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 08:34:32 log 42175 6208778240 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 08:34:33 log 42175 6208778240 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 08:34:33 log 42175 6259257344 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 08:34:34 log 42175 6225604608 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 08:34:34 log 42175 6208778240 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 08:34:38 log 42175 6326562816 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 08:46:34 log 42175 6326562816 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 08:47:59 log 42175 6326562816 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 08:49:41 log 42175 6191951872 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 08:57:33 log 42175 6259257344 Too Many Requests: /cvv/
WARNING 2025-06-13 08:57:33 log 42175 6208778240 Too Many Requests: /favicon.ico
WARNING 2025-06-13 08:57:54 log 42175 6309736448 Too Many Requests: /cvv/
WARNING 2025-06-13 08:57:54 log 42175 6208778240 Too Many Requests: /favicon.ico
WARNING 2025-06-13 09:07:28 log 42175 6377041920 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 09:08:09 log 42175 6377041920 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 09:15:55 log 42175 6225604608 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 10:58:12 log 42175 6191951872 Not Found: /favicon.ico
WARNING 2025-06-13 11:45:25 log 43952 6253129728 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 11:47:14 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 11:49:52 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 11:50:00 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 11:54:34 log 43952 6219476992 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 11:54:42 log 43952 6219476992 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 11:54:44 log 43952 6219476992 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 12:01:02 log 43952 6236303360 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 12:08:30 log 43952 6219476992 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 12:09:06 log 43952 6219476992 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 12:13:57 log 43952 6236303360 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 12:19:08 log 43952 6219476992 Not Found: /favicon.ico
WARNING 2025-06-13 12:32:55 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 12:33:18 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 12:33:20 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 12:33:48 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 12:33:49 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 12:33:49 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 12:33:50 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 12:39:37 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 12:57:12 log 43952 6236303360 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 12:59:14 log 43952 6236303360 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:01:24 log 43952 6236303360 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:02:16 log 43952 6236303360 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:02:17 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:02:52 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:02:54 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:03:03 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:03:03 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:03:17 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:03:18 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:03:23 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:03:23 log 43952 6202650624 Not Found: /favicon.ico
WARNING 2025-06-13 13:03:31 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:03:35 log 43952 6236303360 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:03:37 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:03:40 log 43952 6236303360 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:03:42 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:03:44 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:03:45 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:03:55 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:03:56 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:03:57 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:03:59 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:04:00 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:04:00 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:04:01 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:04:03 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:10:12 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:15:04 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:17:42 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:18:20 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:19:05 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:19:06 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:19:18 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:19:19 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:19:19 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:28:25 log 43952 6253129728 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:28:48 log 43952 6253129728 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:43:14 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:44:46 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:46:09 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:46:58 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:47:00 log 43952 6202650624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:55:51 log 46998 6167719936 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:56:09 log 46998 6167719936 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 13:58:56 log 46998 6184546304 Not Found: /favicon.ico
WARNING 2025-06-13 14:05:52 log 46998 6184546304 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 14:06:45 log 46998 6184546304 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-13 14:09:30 log 50058 6180302848 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-14 04:05:42 log 50058 6180302848 Not Found: /favicon.ico
WARNING 2025-06-14 04:05:58 log 50058 6180302848 Forbidden (Permission denied): /nepal/ticket/ticket/18/change/
Traceback (most recent call last):
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1799, in _changeform_view
    self.save_related(request, form, formsets, not add)
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1255, in save_related
    self.save_formset(request, form, formset, change=change)
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1243, in save_formset
    formset.save()
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/forms/models.py", line 784, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/forms/models.py", line 944, in save_new_objects
    self.new_objects.append(self.save_new(form, commit=commit))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/forms/models.py", line 1142, in save_new
    return super().save_new(form, commit=commit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/forms/models.py", line 757, in save_new
    return form.save(commit=commit)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/forms/models.py", line 542, in save
    self.instance.save()
  File "/Users/iqbal/Desktop/work-history/lotipoti-shop/markcc-seller/markcc_with_seller/ticket/models.py", line 38, in save
    raise PermissionDenied('Only admins can add replies to open tickets')
django.core.exceptions.PermissionDenied: Only admins can add replies to open tickets
WARNING 2025-06-14 04:24:41 log 50058 6163476480 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-14 05:46:55 log 50058 6180302848 Not Found: /favicon.ico
WARNING 2025-06-14 05:48:38 log 50058 6180302848 Too Many Requests: /cvv/
WARNING 2025-06-14 06:05:57 log 93938 6194376704 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-14 06:25:39 log 93938 6193803264 Too Many Requests: /cvv/
WARNING 2025-06-14 06:25:54 log 93938 6211203072 Too Many Requests: /orders/
WARNING 2025-06-14 06:25:55 log 93938 6193803264 Too Many Requests: /orders/
WARNING 2025-06-14 06:25:56 log 93938 6193803264 Too Many Requests: /orders/
WARNING 2025-06-14 06:25:57 log 93938 6193803264 Too Many Requests: /orders/
WARNING 2025-06-14 06:25:59 log 93938 6228029440 Too Many Requests: /cvv/
WARNING 2025-06-14 06:51:09 log 93938 6261108736 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-14 06:51:43 log 93938 6261108736 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-06-14 07:09:01 log 13217 6203633664 Not Found: /favicon.ico
ERROR 2025-06-14 16:01:47 log 51320 6125596672 Internal Server Error: /auth/login/
Traceback (most recent call last):
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/Desktop/work-history/lotipoti-shop/markcc-seller/markcc_without_seller/users/views.py", line 102, in login
    return render(request, 'auth/login.html', {'formcaptcha': formcaptcha})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 698, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 606, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'add_class'
WARNING 2025-06-14 16:01:47 log 51320 6125596672 Not Found: /favicon.ico
ERROR 2025-06-14 16:01:52 log 51320 6125596672 Internal Server Error: /auth/login/
Traceback (most recent call last):
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/Desktop/work-history/lotipoti-shop/markcc-seller/markcc_without_seller/users/views.py", line 102, in login
    return render(request, 'auth/login.html', {'formcaptcha': formcaptcha})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 698, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 606, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'add_class'
ERROR 2025-06-14 16:02:23 log 51320 6125596672 Internal Server Error: /auth/login/
Traceback (most recent call last):
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/Desktop/work-history/lotipoti-shop/markcc-seller/markcc_without_seller/users/views.py", line 102, in login
    return render(request, 'auth/login.html', {'formcaptcha': formcaptcha})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 698, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 606, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'add_class'
ERROR 2025-06-14 16:02:23 log 51320 6125596672 Internal Server Error: /auth/login/
Traceback (most recent call last):
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/Desktop/work-history/lotipoti-shop/markcc-seller/markcc_without_seller/users/views.py", line 102, in login
    return render(request, 'auth/login.html', {'formcaptcha': formcaptcha})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 698, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 606, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'add_class'
ERROR 2025-06-14 16:02:23 log 51320 6125596672 Internal Server Error: /auth/login/
Traceback (most recent call last):
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/Desktop/work-history/lotipoti-shop/markcc-seller/markcc_without_seller/users/views.py", line 102, in login
    return render(request, 'auth/login.html', {'formcaptcha': formcaptcha})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 698, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 606, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'add_class'
ERROR 2025-06-14 16:02:24 log 51320 6125596672 Internal Server Error: /auth/login/
Traceback (most recent call last):
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/Desktop/work-history/lotipoti-shop/markcc-seller/markcc_without_seller/users/views.py", line 102, in login
    return render(request, 'auth/login.html', {'formcaptcha': formcaptcha})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 698, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iqbal/.pyenv/versions/3.11.6/lib/python3.11/site-packages/django/template/base.py", line 606, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'add_class'
WARNING 2025-06-14 16:14:05 log 51320 6125596672 Not Found: /favicon.ico
WARNING 2025-06-14 16:15:14 log 51320 6125596672 Bad Request: /auth/login/
WARNING 2025-06-14 16:15:20 log 51320 6125596672 Bad Request: /auth/login/
WARNING 2025-06-14 16:15:24 log 51320 6125596672 Bad Request: /auth/login/
WARNING 2025-06-14 16:17:35 log 51320 6125596672 Not Found: /favicon.ico
WARNING 2025-06-14 16:17:56 log 51320 6159249408 Bad Request: /auth/login/
WARNING 2025-06-14 16:18:17 log 51320 6125596672 Bad Request: /auth/login/
WARNING 2025-06-14 16:19:34 log 51320 6159249408 Bad Request: /auth/login/
WARNING 2025-06-14 16:19:35 log 51320 6159249408 Bad Request: /auth/login/
WARNING 2025-06-14 16:20:03 log 51320 6159249408 Bad Request: /auth/login/
WARNING 2025-06-14 16:20:03 log 51320 6159249408 Bad Request: /auth/login/
WARNING 2025-06-14 16:20:03 log 51320 6159249408 Bad Request: /auth/login/
WARNING 2025-06-14 16:20:58 log 51320 6142423040 Bad Request: /auth/login/
WARNING 2025-06-14 16:22:33 log 51320 6142423040 Bad Request: /auth/login/
WARNING 2025-06-14 16:25:20 log 51320 6159249408 Bad Request: /auth/register/
WARNING 2025-06-14 16:25:33 log 51320 6159249408 Bad Request: /auth/register/
WARNING 2025-06-14 16:25:34 log 51320 6159249408 Bad Request: /auth/register/
WARNING 2025-06-14 16:27:05 log 51320 6325039104 Bad Request: /auth/register/
WARNING 2025-06-14 16:31:57 log 51320 6142423040 Bad Request: /auth/register/
WARNING 2025-06-14 16:50:04 log 51320 6125596672 Not Found: /favicon.ico
WARNING 2025-06-14 16:53:48 log 72856 6186364928 Not Found: /favicon.ico
ERROR 2025-06-14 17:25:34 log 72856 6168965120 Service Unavailable: /
ERROR 2025-06-14 17:26:39 log 72856 6168965120 Service Unavailable: /
ERROR 2025-06-14 17:26:41 log 72856 6168965120 Service Unavailable: /
ERROR 2025-06-14 17:26:41 log 72856 6168965120 Service Unavailable: /favicon.ico
ERROR 2025-06-14 17:27:03 log 72856 6168965120 Service Unavailable: /
ERROR 2025-06-14 17:27:03 log 72856 6168965120 Service Unavailable: /
ERROR 2025-06-14 17:27:03 log 72856 6168965120 Service Unavailable: /
ERROR 2025-06-14 17:27:19 log 72856 6168965120 Service Unavailable: /auth/login/
ERROR 2025-06-14 17:27:21 log 72856 6168965120 Service Unavailable: /auth/login/
ERROR 2025-06-14 17:28:15 log 72856 6202617856 Service Unavailable: /auth/register/
ERROR 2025-06-14 17:29:23 log 72856 6168965120 Service Unavailable: /auth/register/
ERROR 2025-06-14 17:29:24 log 72856 6168965120 Service Unavailable: /auth/register/
WARNING 2025-06-14 17:31:00 log 72856 6168965120 Bad Request: /auth/register/
